name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  windows:
    uses: ./.github/workflows/unit-tests.yml
    with:
      matrix: |
        {
          "include": [
            { "runner": "windows-latest", "os": "windows", "arch": "x64",   "framework": "net472" },
            { "runner": "windows-latest", "os": "windows", "arch": "x64",   "framework": "net8.0" },
            { "runner": "windows-latest", "os": "windows", "arch": "x64",   "framework": "net10.0" },
            { "runner": "windows-11-arm", "os": "windows", "arch": "arm64", "framework": "net8.0" },
            { "runner": "windows-11-arm", "os": "windows", "arch": "arm64", "framework": "net10.0" }
          ]
        }
